### PR TITLE
adaptiveLastN and channelLastN do not work in jitsi-meet-react

### PR DESCRIPTION
**Pull request by liu1083947028**
Hi all
image
image

It does not work. 

image

Is somewhere wrong? Thanks

### CODE REVIEW

**Comment by tsareg** [comment]
Something wrong is with this PR. I see commit from @yanas here, but message and description is about completely different issue.

**Comment by tsareg** [comment]
@liu1083947028 it seems you're trying to merge in something different.
As for the issue you mentioned, React project is under heavy development now, so lots of stuff is not working yet. But PRs are welcome!

**Comment by liu1083947028** [comment]
@tsareg  Thanks your replay first.  and i want to know will you add oudspeaker on in jitsi-meet-react?

or can you give me some suggest about how can i set oudspeaker on in react?

Thanks

**Comment by tsareg** [comment]
@liu1083947028 We're going to fully re-assemble all jitsi-meet functionality, but I don't know when it's going to happen.

**Pull request closed without merging**
