### PR TITLE
Only inject audio for remote tracks.

### PR DESCRIPTION
**Pull request by legastero**

### CODE REVIEW

**Comment by tsareg** [comment]
Well, in jitsi-meet we always add <audio> element - https://github.com/jitsi/jitsi-meet/blob/master/modules/UI/UI.js#L510-L522. Though it's muted.

I think this is done for a reason, but we should ask other people about that.

**Comment by tsareg** [comment]
@paweldomas says about having "audio" tag for local participant in jitsi-meet:

I don't think there is any reason, eventually it would be worth checking if that's not used for local audio levels
and if not it should be ok to remove it
Audio levels are generate in lib-jitsi-meet which is shared by both projects
if they do not require <audio> element to work I think it's fine to remove that from react project, about jitsi-meet we're going to migrate to react anyway, so as long as it's not causing any issues there it could remain untouched. However it might make sense to remove it from there as well for the sake of consistency. Doing so may reveal eventual other issues, so maybe it would be good to start by removing it from meet to be sure it's not used for other purposes

**Comment by tsareg** [comment]
So @legastero and @lyubomir, aren't we going to study the behavior in jitsi-meet before going with that?

**Comment by lyubomir** [comment]
@tsareg, if you feel that it's a goal worth pursuing, please feel free to dedicate time to it.

**Pull request merged**
