### PR TITLE
Deal with lib-jitsi-meet's draconian addTrack

### PR DESCRIPTION
**Pull request by lyubomir**
Lib-jitsi-meet's JitsiConference#addTrack is excessively harsh and
severe and may throw an error if we try to add one and the same track
multiple times. Attempt to prevent such adding in order to reduce the
risks of such a throw.

### CODE REVIEW

**Comment by tsareg** [comment]
OK for me

**Comment by liu1083947028** [comment]
@lyubomir 

Are you merged this commit to master?

Why can i see this error?

image

**Comment by tsareg** [comment]
@liu1083947028 Do you receive this after ending the conference and re-joining a new one? If yes, it's a known bug, we're working on it.

**Comment by liu1083947028** [comment]
@tsareg  I receive this after ending the conference and re-joining a new one.

We hope to resolve as soon as possible.

**Comment by tsareg** [comment]
@liu1083947028 this is fixed by PR https://github.com/jitsi/jitsi-meet-react/pull/39

**Comment by liu1083947028** [comment]
@tsareg Thanks, i checked it.

**Pull request merged**
