### PR TITLE
Introduces eslint with basic set of validation rules

### PR DESCRIPTION
**Pull request by tsareg**
Introduces eslint with basic set of validation rules.
Pre-commit hook will run eslint to not allow inappropriate code.

### CODE REVIEW

**Comment by tsareg** [comment]
Please, do not merge for now.

**Comment by tsareg** [comment]
Can be merged now

**Comment by lyubomir** [comment]
This is not specific to @tsareg's PR but I'm going to say the following here because this PR is an example:
- Please don't bundle up multiple unrelated commits into 1 PR. For example, requiring the strophe library to fix some connection issue has nothing to do with eslint.
- If you accidentally remove files in a commit in a PR, don't have a second commit in the same PR which restores them. Please squash/fixup/whatever before you create the PR. The accidental removal and the followup restoration (in 1 PR) is something that happened on your local clone and it doesn't concern other people. Don't waste the time of the reviewers.

**Comment by lyubomir** [comment]
Thank you!

**Pull request merged**
